options:
  install-sources:
    type: string
    default: |
      - "ppa:opencontrail/ppa"
      - "ppa:opencontrail/r2.20"
    description: Package sources for install
  install-keys:
    type: string
    description: Apt keys for package install sources
  openstack-origin:
    type: string
    default: distro
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.

      Supported Cloud Archive sources include: cloud:precise-folsom,
      cloud:precise-folsom/updates, cloud:precise-folsom/staging,
      cloud:precise-folsom/proposed.
  vip:
    type: string
    description: |
      Virtual IP address to use when services are related in a High Availability
      configuration.
  cassandra-units:
    type: int
    default: 1
    description: Minimum number of units required in cassandra relation
  kafka-units:
    type: int
    default: 1
    description: Minimum number of units required in kafka relation
