options:
  control-network:
    type: string
    description: |
      The IP address and netmask of the control network (e.g. 192.168.0.0/24).
      This network will be used for Contrail endpoints.
      If not specified, default network will be used.
  auth-mode:
    type: string
    default: cloud-admin
    description: |
      It represents 'aaa_mode' configuration key of Contrail.
      Can be one of: 'rbac', 'cloud-admin' or 'no-auth'
      Authentication mode. Detailed information can be found in the Contrail documentation.
  cloud-admin-role:
    type: string
    default: admin
    description: |
      Role name in keystone for users that have full access to everything.
  global-read-only-role:
    type: string
    description: |
      Role name in keystone for users that have read-only access to everything.
  vip:
    type: string
    description: |
      Contrail API VIP to be used for configuring client-side software like neutron plugin.
      (to be set up also in KeepAlived charm configuration if it’s used for HA)
      Private IP of the first Contrail API unit will be used if not set.
