options:
  zk-port:
    type: int
    default: 2181
    description: ZooKeeper Client Access Port
  source:
    type: string
    default: archive
    description: |
      Location and packages to install zookeeper:
      .
       * archive: Install using the zookeeperd package from the main
                  Ubuntu Archive.
       * dev:     Install using the hadoop-zookeeper-server package from
                  ppa:hadoop-ubuntu/dev.
       * testing: Install using the hadoop-zookeeper-server package from
                  ppa:hadoop-ubuntu/testing.
       * stable:  Install using the hadoop-zookeeper-server package from
                  ppa:hadoop-ubuntu/stable.
      .
      The packages provides in the hadoop-ubuntu team PPA's are based
      directly on upstream ZooKeeper releases but are not fully built from
      source.
  default_weight:
    type: int
    default: 1
    description: default weight
  default_group:
    type: int
    default: 0
    description: default group
  external_server:
    type: string
    default: ""
    description: |
      Extra servers ( external to juju ) to add
      to zoo.cnf.  Format should be id:group:weight:host:port:port
      group can be defined as "default" as opposed to a number to use
      the default_group defined above
