options:
  install-sources:
    type: string
    description: Package sources for install
  install-keys:
    type: string
    description: Apt keys for package install sources
  physical-interface:
    type: string
    description: |
      Specify the interface to install vhost0 on. If left empty, vhost0 will
      be installed on the default gateway interface.
  vhost-gateway:
    type: string
    default: auto
    description: |
      Specify the gateway for vhost0, either an IPv4 address or keyword 'auto'.
      'auto' will set gateway automatically based on host's existing routes.
  control-network:
    type: string
    description: |
      The IP address and netmask of the control network channel (e.g. 192.168.0.0/24).
      Default is to use vRouter interface that will be created.
  remove-juju-bridge:
    type: boolean
    default: true
    description: |
      Juju on MAAS creates bridges for deploying LXD/LXC and KVM workloads.
      Enable this to remove such a bridge if you want to install vhost0 directly
      on the underlying interface.
